/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        background:                  '#F7F3EA',
        surface:                     '#FFFFFF',
        'surface-low':               '#F7F3EA',
        'surface-dim':               '#E5E7EB',
        'surface-container':         '#F7F3EA',
        'surface-container-low':     '#FFFFFF',
        'surface-container-high':    '#E5E7EB',
        'surface-container-highest': '#D6D9DE',
        'surface-container-lowest':  '#FFFFFF',
        'on-surface':                '#111827',
        'on-surface-variant':        '#4B5563',
        outline:                     '#9CA3AF',
        'outline-variant':           '#E5E7EB',
        primary:                     '#1b2e4b',
        'on-primary':                '#F7F3EA',
        'primary-container':         '#E5E7EB',
        'on-primary-container':      '#1b2e4b',
        secondary:                   '#D6B56D',
        'on-secondary':              '#111827',
        tertiary:                    '#111827',
        'on-tertiary':               '#F7F3EA',
        'inverse-surface':           '#1b2e4b',
        'inverse-on-surface':        '#F7F3EA',
        gold:                        '#D6B56D',
        'gold-dark':                 '#9E7D36',
      },
      fontFamily: {
        headline: ['Noto Serif', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
        serif: ['Noto Serif', 'serif'],
        sans: ['Manrope', 'sans-serif'],
        hand: ['Caveat', 'Architects Daughter', 'cursive'],
      },
      backgroundImage: {
        'gold-shimmer': 'none',
      },
    },
  },
  plugins: [],
}
