/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        background:                  '#faf8f4',
        surface:                     '#f3ede5',
        'surface-low':               '#f7f3ee',
        'surface-dim':               '#ede5d8',
        'surface-container':         '#f3ede5',
        'surface-container-low':     '#f7f3ee',
        'surface-container-high':    '#e8ddd0',
        'surface-container-highest': '#ddd0be',
        'surface-container-lowest':  '#faf8f4',
        'on-surface':                '#1b2e4b',
        'on-surface-variant':        '#4a6080',
        outline:                     '#c5b9a8',
        'outline-variant':           '#ddd0be',
        primary:                     '#1b2e4b',
        'on-primary':                '#faf8f4',
        'primary-container':         '#dce8f5',
        'on-primary-container':      '#1b2e4b',
        secondary:                   '#b8963e',
        'on-secondary':              '#faf8f4',
        tertiary:                    '#4a6080',
        'on-tertiary':               '#faf8f4',
        'inverse-surface':           '#1b2e4b',
        'inverse-on-surface':        '#faf8f4',
        gold:                        '#b8963e',
        'gold-dark':                 '#8a6d28',
      },
      fontFamily: {
        headline: ['Noto Serif', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
        serif: ['Noto Serif', 'serif'],
        sans: ['Manrope', 'sans-serif'],
        hand: ['Caveat', 'Architects Daughter', 'cursive'],
      },
      backgroundImage: {
        'gold-shimmer': 'none',
      },
    },
  },
  plugins: [],
}
